### ISSUE TITLE
Adding ChatGPT API

### ISSUE THREAD

**Issue by Timothyxxx** [HazyResearch/manifest#43]
Hi, could we have ChatGPT API in the manifest, since there have been a lot of ones to call it in GitHub these days, I think maybe many fans(of course including me) want to use that inside manifest for the unified interface to run more interesting demos and research experiments. 
I can help with it if you would like to.😉

**Comment by lorr1** [comment]
Hey Timothy! Yes, if you'd like to make a PR that'd be great. ChatGPT is on the list to add for sure!

**Comment by lorr1** [comment]
Just added it

See https://github.com/HazyResearch/manifest/blob/main/examples/manifest_chatgpt.ipynb

It's not on pip yet so make sure to go off of the main branch. You'll need to install https://github.com/terry3041/pyChatGPT
