### ISSUE TITLE
Unable to initialize non-standard models from commandline

### ISSUE THREAD

**Issue by slush0** [HazyResearch/manifest#54]
## Description of the bug

I'm aware of ```--model_generation_type```, but currently it allows to specify only "casual" model types. There's plenty of HF models not defined in MODEL_REGISTRY, which cannot be initialized without adding more generation types, or without reworking the mechanism to be more dynamic. For example, Manifest is not aware of BLOOMZ model, which uses ```BloomForCausalLM```.

## Expected behavior
Ability to define (at least) all models imported from transformers in ```huggingface.py```.

**Comment by lorr1** [comment]
Hey! Happy to add more types. If you load the BLOOMZ model, for example, with a huggingface pipeline, what type keyword do you use? Is it not `text-generation`?

**Comment by slush0** [comment]
I'm not sure if I understand the question well, but it seems Bloom has various heads available. According to https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/models/auto/modeling_auto.py, there're definitions for multiple pipeline types containing Bloom: BloomForCausalLM, BloomForSequenceClassification, BloomForQuestionAnswering...

**Comment by lorr1** [comment]
Just checking in, is this still an issue?
