### ISSUE TITLE
Output tokens in addition to token_logprobs

### ISSUE THREAD

**Issue by einarbmag** [HazyResearch/manifest#63]
## Description of the feature request
I'm working on a use case where I want to assign scores to different parts of the LLM output. The PR adding the token_logprobs (https://github.com/HazyResearch/manifest/pull/59) goes a long way, but I think I need the corresponding tokens as well if I'm going to get the scores for a specific substring of the output. 

## Description of the solution you'd like
Probably just an additional field in the he output containing the tokenised output? Not the token ids, the word pieces. 

## Description of the alternatives you've considered
I can have the right tokenizer loaded locally to work out the token logprob alignment. Slightly defeats the promise of the Manifest approach though.

**Comment by lorr1** [comment]
Will be added in https://github.com/HazyResearch/manifest/pull/68. Note that if you give it a batch, it will pad to the left so you will get some pad tokens.

**Comment by lorr1** [comment]
You should be good to go with `score_prompt`.

```
from manifest import Manifest
client = Manifest(client_name="huggingface", client_connection="http://localhost:6000")
res = client.score_prompt("Apples are great")
>>> res
{'generation_key': 'choices', 'logits_key': 'token_logprobs', 'item_key': 'text', 'item_dtype': None, 'response': {'choices': [{'text': 'Apples are great', 'logprob': -37.40739059448242, 'tokens': [4677, 829, 389, 1049], 'token_logprobs': [-6.315037250518799, -12.288839340209961, -9.455543518066406, -9.347970962524414]}]}, 'cached': False, 'request_params': {'prompt': 'Apples are great', 'n': 1, 'request_type': 'score_prompt', 'temperature': 1.0, 'max_tokens': 10, 'top_p': 1.0, 'top_k': 50, 'do_sample': True, 'repetition_penalty': 1.0, 'model_name': 'EleutherAI/gpt-neo-125M', 'model_path': 'EleutherAI/gpt-neo-125M'}}
>>> res["response"]
{'choices': [{'text': 'Apples are great', 'logprob': -37.40739059448242, 'tokens': [4677, 829, 389, 1049], 'token_logprobs': [-6.315037250518799, -12.288839340209961, -9.455543518066406, -9.347970962524414]}]}
```
