### ISSUE TITLE
Asynchronous run?

### ISSUE THREAD

**Issue by srush** [HazyResearch/manifest#64]
Was curious if you were planning on adding asynchronous calls? I've been using async_openai for https://github.com/srush/minichain . Would be easier to switch to manifest for the backend. However the async thing is kind of nice.

**Comment by lorr1** [comment]
Ya, it's been on the list to add arun support basically. At least with Openai as they support it already. Will add to the list of new features.

**Comment by lorr1** [comment]
Will be added in https://github.com/HazyResearch/manifest/pull/68. Added an example script showing usage with openai.

**Comment by lorr1** [comment]
See https://github.com/HazyResearch/manifest/blob/main/examples/manifest_async.py
