### ISSUE TITLE
Docs for Embeddings?

### ISSUE THREAD

**Issue by srush** [HazyResearch/manifest#66]
Is there a way to embed text with OpenAI for Manifest? I couldn't find docs.

**Comment by lorr1** [comment]
Not yet. There's been some discussion around adding embedding functions and there's preliminary rough support in the HF models. The caching layer is ready so it's just a matter of adding the request object, function calls, and making sure pipes work.

**Comment by lorr1** [comment]
Embeddings added to `main`. I'm working on adding embeddings to local models (e.g. SentenceTransformer style) this week before pushing to pip.

See first half of notebook https://github.com/HazyResearch/manifest/blob/main/examples/manifest_embedding.ipynb.

Caching is also supported.
