### ISSUE TITLE
ChatGPT support

### ISSUE THREAD

**Issue by srush** [HazyResearch/manifest#67]
(while I'm adding requests)

ChatGPT API call requires different options Chat vs. Completions. Was going to add this to my lib, but am going to just move to manifest.

**Comment by lorr1** [comment]
Will be added in https://github.com/HazyResearch/manifest/pull/68. I added a `openaichat` client. It hooks into all the main prompt stuff (so I don't support conversations) per say and just cast everything as user content.

**Comment by lorr1** [comment]
```
manifest = Manifest(
    client_name="openaichat",
)
manifest.run("test")
```
